import 'package:flutter/material.dart';
import '../../data/models/ai_order_proposal_model.dart';
import '../../data/ai_build_service.dart';
import 'ai_order_submitted_screen.dart';

/// Screen displaying Member 04 Order Planning Agent proposal
/// Matches UI 4 (ui4.png) in PCForge Agentic AI Workflow specifications:
/// "Flutter · order proposal screen — customer approves the build, not the payment"
class AiOrderProposalScreen extends StatefulWidget {
  final AiOrderProposalResultModel proposalResult;
  final Map<String, dynamic> rawComponents;

  const AiOrderProposalScreen({
    super.key,
    required this.proposalResult,
    required this.rawComponents,
  });

  @override
  State<AiOrderProposalScreen> createState() => _AiOrderProposalScreenState();
}

class _AiOrderProposalScreenState extends State<AiOrderProposalScreen> {
  late AiOrderProposalModel _proposal;
  final TextEditingController _promoController = TextEditingController();
  bool _isApplyingPromo = false;
  bool _showTrace = false;
  bool _showComponentList = false;

  @override
  void initState() {
    super.initState();
    final prop = widget.proposalResult.proposal;
    if (prop == null) {
      throw StateError('AiOrderProposalScreen requires a valid proposal generated by the AI Order Planning Agent.');
    }
    _proposal = prop;
    _promoController.text = _proposal.pricing.discountCode ?? '';
  }

  @override
  void dispose() {
    _promoController.dispose();
    super.dispose();
  }

  Future<void> _handleApplyPromo() async {
    final code = _promoController.text.trim();
    if (code.isEmpty) return;

    setState(() => _isApplyingPromo = true);

    final updatedResult = await AiBuildService.instance.createOrderProposal(
      reservationId: _proposal.reservationId,
      buildName: _proposal.buildName,
      components: widget.rawComponents,
      promoCode: code,
      currency: _proposal.pricing.currency,
    );

    if (!mounted) return;
    setState(() => _isApplyingPromo = false);

    if (updatedResult.success && updatedResult.proposal != null) {
      setState(() {
        _proposal = updatedResult.proposal!;
      });
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          backgroundColor: const Color(0xFF10B981),
          content: Text('Voucher "${code.toUpperCase()}" recalculated by Order Planning Agent!'),
        ),
      );
    } else {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          backgroundColor: const Color(0xFFEF4444),
          content: Text(updatedResult.error ?? 'Invalid voucher code.'),
        ),
      );
    }
  }

  Future<void> _handleApproveOrder() async {
    // Show loading dialog while saving to backend
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (ctx) => PopScope(
        canPop: false,
        child: Dialog(
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
          child: const Padding(
            padding: EdgeInsets.symmetric(horizontal: 24, vertical: 28),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                CircularProgressIndicator(
                  valueColor: AlwaysStoppedAnimation<Color>(Color(0xFF5B4DFF)),
                ),
                SizedBox(height: 20),
                Text(
                  'Saving Order Proposal...',
                  style: TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.w700,
                    color: Color(0xFF0F172A),
                  ),
                ),
                SizedBox(height: 8),
                Text(
                  'Submitting build to React technician queue for human inspection. No payment is charged yet.',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    fontSize: 12.5,
                    color: Color(0xFF64748B),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );

    final submitted = await AiBuildService.instance.submitApprovedOrder(
      proposalId: _proposal.proposalId,
      orderNumber: _proposal.orderNumber,
      reservationId: _proposal.reservationId,
      buildName: _proposal.buildName,
      totalAmount: _proposal.pricing.totalPrice,
      formattedTotal: _proposal.pricing.formattedTotal,
      shippingAddress: 'Colombo, Western Province',
      components: _proposal.components,
    );

    if (!mounted) return;
    Navigator.of(context, rootNavigator: true).pop(); // Dismiss loading dialog

    if (submitted != null) {
      Navigator.push(
        context,
        MaterialPageRoute(
          builder: (_) => AiOrderSubmittedScreen(
            submittedOrder: submitted,
            buildName: _proposal.buildName,
          ),
        ),
      );
    } else {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          backgroundColor: Color(0xFFEF4444),
          content: Text('Failed to submit order to backend. Please check backend connection.'),
        ),
      );
    }
  }

  void _handleRejectOrder() {
    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        title: const Text('Request Build Revision?'),
        content: const Text(
          'Would you like to return to the AI Build Agent to modify specifications or components?',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx),
            child: const Text('Cancel'),
          ),
          ElevatedButton(
            style: ElevatedButton.styleFrom(
              backgroundColor: const Color(0xFF5B4DFF),
              foregroundColor: Colors.white,
            ),
            onPressed: () {
              Navigator.pop(ctx);
              Navigator.pop(context); // Return to previous step
            },
            child: const Text('Revise Build'),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final pricing = _proposal.pricing;

    return Scaffold(
      backgroundColor: const Color(0xFFF8FAFC),
      appBar: AppBar(
        elevation: 0,
        backgroundColor: const Color(0xFF5B4DFF),
        foregroundColor: Colors.white,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_new_rounded, size: 18),
          onPressed: () => Navigator.pop(context),
        ),
        title: const Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Confirm your order',
              style: TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.w800,
                letterSpacing: -0.3,
                color: Colors.white,
              ),
            ),
            Text(
              'Order Planning Agent • Step 4',
              style: TextStyle(
                fontSize: 11,
                fontWeight: FontWeight.w500,
                color: Color(0xFFE0E7FF),
              ),
            ),
          ],
        ),
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 20),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // 1. Amber Badge matching ui4.png: "Waiting for your approval"
              _buildApprovalPill(),

              const SizedBox(height: 16),

              // 2. Order Summary Card matching ui4.png exactly
              _buildOrderSummaryCard(pricing),

              const SizedBox(height: 18),

              // 3. Coupon Promo Code Input Field
              _buildPromoSection(),

              const SizedBox(height: 18),

              // 4. Expandable Components Drawer
              _buildComponentsAccordion(),

              const SizedBox(height: 12),

              // 5. Agent Reasoning Trace Drawer
              _buildTraceAccordion(),

              const SizedBox(height: 24),

              // 6. Action Buttons matching ui4.png
              _buildActionButtons(),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildApprovalPill() {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 7),
      decoration: BoxDecoration(
        color: const Color(0xFFFEF3C7), // Warm amber matching ui4.png
        borderRadius: BorderRadius.circular(16),
      ),
      child: Text(
        _proposal.statusLabel,
        style: const TextStyle(
          fontSize: 13.5,
          fontWeight: FontWeight.w700,
          color: Color(0xFFB45309), // Amber text
          letterSpacing: -0.2,
        ),
      ),
    );
  }

  Widget _buildOrderSummaryCard(AiPricingBreakdownModel pricing) {
    return Container(
      padding: const EdgeInsets.all(22),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(20),
        border: Border.all(color: const Color(0xFFE2E8F0)),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.04),
            blurRadius: 16,
            offset: const Offset(0, 6),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text(
            'Order Summary',
            style: TextStyle(
              fontSize: 17,
              fontWeight: FontWeight.w800,
              color: Color(0xFF0F172A),
              letterSpacing: -0.3,
            ),
          ),
          const SizedBox(height: 18),

          // Row 1: Components (8)
          _buildSummaryRow(
            label: 'Components (${_proposal.componentsCount})',
            value: pricing.formattedSubtotal,
            isBold: false,
          ),
          const SizedBox(height: 14),

          // Row 2: Discount (WELCOME5)
          _buildSummaryRow(
            label: pricing.discountLabel ?? 'Discount',
            value: pricing.formattedDiscount,
            isBold: false,
            valueColor: const Color(0xFF10B981), // Green for discount deduction
          ),
          const SizedBox(height: 14),

          // Row 3: Delivery
          _buildSummaryRow(
            label: 'Delivery',
            value: pricing.formattedDelivery,
            isBold: false,
          ),

          const SizedBox(height: 16),
          const Divider(color: Color(0xFF0F172A), thickness: 1.5, height: 1),
          const SizedBox(height: 16),

          // Row 4: Total
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Text(
                'Total',
                style: TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.w800,
                  color: Color(0xFF0F172A),
                ),
              ),
              Text(
                pricing.formattedTotal,
                style: const TextStyle(
                  fontSize: 19,
                  fontWeight: FontWeight.w900,
                  color: Color(0xFF0F172A),
                  letterSpacing: -0.4,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildSummaryRow({
    required String label,
    required String value,
    required bool isBold,
    Color? valueColor,
  }) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(
          label,
          style: TextStyle(
            fontSize: 14.5,
            fontWeight: isBold ? FontWeight.w700 : FontWeight.w500,
            color: const Color(0xFF64748B),
          ),
        ),
        Text(
          value,
          style: TextStyle(
            fontSize: 15,
            fontWeight: isBold ? FontWeight.w800 : FontWeight.w700,
            color: valueColor ?? const Color(0xFF0F172A),
          ),
        ),
      ],
    );
  }

  Widget _buildPromoSection() {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: const Color(0xFFE2E8F0)),
      ),
      child: Row(
        children: [
          const Icon(Icons.local_offer_outlined, color: Color(0xFF5B4DFF), size: 20),
          const SizedBox(width: 12),
          Expanded(
            child: TextField(
              controller: _promoController,
              textCapitalization: TextCapitalization.characters,
              decoration: const InputDecoration(
                hintText: 'Enter coupon code',
                isDense: true,
                border: InputBorder.none,
                hintStyle: TextStyle(fontSize: 13.5, color: Color(0xFF94A3B8)),
              ),
              style: const TextStyle(
                fontSize: 14,
                fontWeight: FontWeight.w700,
                color: Color(0xFF0F172A),
              ),
            ),
          ),
          const SizedBox(width: 8),
          SizedBox(
            height: 36,
            child: ElevatedButton(
              onPressed: _isApplyingPromo ? null : _handleApplyPromo,
              style: ElevatedButton.styleFrom(
                backgroundColor: const Color(0xFF5B4DFF),
                foregroundColor: Colors.white,
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                padding: const EdgeInsets.symmetric(horizontal: 14),
                elevation: 0,
              ),
              child: _isApplyingPromo
                  ? const SizedBox(
                      width: 14,
                      height: 14,
                      child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white),
                    )
                  : const Text('Apply', style: TextStyle(fontSize: 12.5, fontWeight: FontWeight.w700)),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildComponentsAccordion() {
    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: const Color(0xFFE2E8F0)),
      ),
      child: Theme(
        data: Theme.of(context).copyWith(dividerColor: Colors.transparent),
        child: ExpansionTile(
          initiallyExpanded: _showComponentList,
          onExpansionChanged: (val) => setState(() => _showComponentList = val),
          title: Text(
            'Itemized Hardware Components (${_proposal.components.length})',
            style: const TextStyle(
              fontSize: 13.5,
              fontWeight: FontWeight.w700,
              color: Color(0xFF334155),
            ),
          ),
          children: [
            Padding(
              padding: const EdgeInsets.fromLTRB(16, 0, 16, 16),
              child: Column(
                children: _proposal.components.map((item) {
                  return Padding(
                    padding: const EdgeInsets.symmetric(vertical: 6),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Expanded(
                          child: Text(
                            item.name,
                            style: const TextStyle(
                              fontSize: 13,
                              fontWeight: FontWeight.w500,
                              color: Color(0xFF1E293B),
                            ),
                            maxLines: 1,
                            overflow: TextOverflow.ellipsis,
                          ),
                        ),
                        const SizedBox(width: 8),
                        Text(
                          '${_proposal.pricing.currency} ${item.unitPrice.toStringAsFixed(0)}',
                          style: const TextStyle(
                            fontSize: 13,
                            fontWeight: FontWeight.w700,
                            color: Color(0xFF0F172A),
                          ),
                        ),
                      ],
                    ),
                  );
                }).toList(),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildTraceAccordion() {
    final trace = widget.proposalResult.agentTrace;
    if (trace.isEmpty) return const SizedBox.shrink();

    return Container(
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: const Color(0xFFE2E8F0)),
      ),
      child: Theme(
        data: Theme.of(context).copyWith(dividerColor: Colors.transparent),
        child: ExpansionTile(
          initiallyExpanded: _showTrace,
          onExpansionChanged: (val) => setState(() => _showTrace = val),
          title: Text(
            'Agent Reasoning & Tool Calls (${trace.length} turns)',
            style: const TextStyle(
              fontSize: 13,
              fontWeight: FontWeight.w600,
              color: Color(0xFF64748B),
            ),
          ),
          children: [
            Container(
              margin: const EdgeInsets.fromLTRB(16, 0, 16, 16),
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: const Color(0xFFF8FAFC),
                borderRadius: BorderRadius.circular(12),
                border: Border.all(color: const Color(0xFFE2E8F0)),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: trace.map((t) {
                  return Padding(
                    padding: const EdgeInsets.only(bottom: 6),
                    child: Text(
                      t,
                      style: const TextStyle(
                        fontSize: 11.5,
                        fontFamily: 'monospace',
                        color: Color(0xFF334155),
                      ),
                    ),
                  );
                }).toList(),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildActionButtons() {
    return Column(
      children: [
        // Primary Button: "Approve Order" matching ui4.png
        SizedBox(
          width: double.infinity,
          height: 52,
          child: ElevatedButton(
            onPressed: _handleApproveOrder,
            style: ElevatedButton.styleFrom(
              backgroundColor: const Color(0xFF5B4DFF), // Purple matching ui4.png
              foregroundColor: Colors.white,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(16),
              ),
              elevation: 3,
              shadowColor: const Color(0xFF5B4DFF).withValues(alpha: 0.4),
            ),
            child: const Text(
              'Approve Order',
              style: TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.w700,
              ),
            ),
          ),
        ),
        const SizedBox(height: 12),

        // Outlined Button: "Reject / Request revision" matching ui4.png
        SizedBox(
          width: double.infinity,
          height: 50,
          child: OutlinedButton(
            onPressed: _handleRejectOrder,
            style: OutlinedButton.styleFrom(
              foregroundColor: const Color(0xFF5B4DFF),
              side: const BorderSide(color: Color(0xFF5B4DFF), width: 1.5),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(16),
              ),
            ),
            child: const Text(
              'Reject / Request revision',
              style: TextStyle(
                fontSize: 15,
                fontWeight: FontWeight.w700,
              ),
            ),
          ),
        ),
      ],
    );
  }
}
