"""
Order Planning Agent Models — PCForge (Member 04)
=================================================
Defines structured data contracts for:
  - Component item pricing
  - Financial breakdown (Subtotal, Discount, Delivery, Total)
  - Formal Order Proposal (Status: WAITING_FOR_APPROVAL)
  - API request & response schemas
"""

from typing import Dict, List, Optional, Any
from pydantic import BaseModel, Field


class OrderPricingItem(BaseModel):
    """An individual item in the priced order proposal."""
    product_id: int = Field(description="Unique product ID")
    slot: str = Field(default="", description="Component slot: cpu, motherboard, ram, etc.")
    name: str = Field(description="Commercial name of the part")
    unit_price: float = Field(default=0.0, description="Unit price in store currency")
    quantity: int = Field(default=1, description="Quantity")
    total_price: float = Field(default=0.0, description="unit_price * quantity")


class PricingBreakdown(BaseModel):
    """Detailed financial breakdown matching UI 4 in PCForge AI Workflow."""
    currency: str = Field(default="LKR", description="Currency symbol: LKR")
    subtotal: float = Field(default=0.0, description="Sum of component prices before discounts and shipping")
    discount_code: Optional[str] = Field(default=None, description="Applied promo code (e.g. WELCOME5)")
    discount_amount: float = Field(default=0.0, description="Total discount deducted from subtotal")
    discount_label: Optional[str] = Field(default=None, description="Human label, e.g. 'Discount (WELCOME5)'")
    delivery_method: str = Field(default="Standard Delivery", description="Shipping tier selected")
    delivery_fee: float = Field(default=2500.0, description="Delivery fee")
    total_price: float = Field(default=0.0, description="Subtotal - discount_amount + delivery_fee")
    
    # Pre-formatted strings for direct UI rendering matching ui4.png exactly
    formatted_subtotal: str = Field(default="Rs. 0", description="Formatted subtotal display string")
    formatted_discount: str = Field(default="- Rs. 0", description="Formatted discount display string")
    formatted_delivery: str = Field(default="Rs. 0", description="Formatted delivery display string")
    formatted_total: str = Field(default="Rs. 0", description="Formatted total display string")


class OrderProposal(BaseModel):
    """The formal order proposal generated by Member 04 Order Planning Agent.
    Strictly holds status WAITING_FOR_APPROVAL until the customer taps 'Approve Order'.
    """
    proposal_id: str = Field(default="", description="Unique proposal identifier: PROP-XXXXXXXX")
    order_number: str = Field(default="PCF-10492", description="Formatted order reference: PCF-XXXXX")
    build_name: str = Field(default="Custom PCForge Rig", description="Build designation")
    reservation_id: str = Field(default="", description="15-minute warehouse stock reservation hold ID")
    status: str = Field(default="WAITING_FOR_APPROVAL", description="UI 4 status: WAITING_FOR_APPROVAL")
    status_label: str = Field(default="Waiting for your approval", description="Amber badge label in UI 4")
    components_count: int = Field(default=8, description="Number of components included in the build")
    pricing: PricingBreakdown = Field(default_factory=PricingBreakdown, description="Itemized financial breakdown")
    components: List[OrderPricingItem] = Field(default_factory=list, description="Priced components list")
    estimated_delivery: str = Field(default="3-5 business days", description="Estimated shipping timeframe")
    technician_notice: str = Field(
        default="We'll notify you once a technician has checked your build — usually within a few hours.",
        description="Notice shown to customer upon approval (UI 5)"
    )


class OrderPlanningRequest(BaseModel):
    """Payload sent to Member 04 to price an approved, stock-verified build."""
    reservation_id: str = Field(default="", description="Warehouse reservation ID from Member 02")
    build_name: str = Field(default="Custom PCForge Rig", description="Name of the PC build")
    components: Dict[str, Any] = Field(
        description="Components dictionary from Member 02 or Member 03 (slot -> details/price)"
    )
    promo_code: Optional[str] = Field(default="WELCOME5", description="Customer coupon code")
    shipping_method: Optional[str] = Field(default="standard", description="standard, express, or pickup")
    shipping_address: Optional[str] = Field(default="Colombo, Western Province", description="Destination city/address")
    currency: Optional[str] = Field(default="LKR", description="Display currency symbol (default LKR)")
    session_id: Optional[str] = Field(default=None, description="Optional conversational session ID")
    coupons: Optional[List[Dict[str, Any]]] = Field(default=None, description="Active promotional coupons context passed from ASP.NET Core")


class OrderProposalResponse(BaseModel):
    """Complete response returned by Member 04 endpoint."""
    success: bool = Field(default=True, description="True if proposal generated successfully")
    proposal: Optional[OrderProposal] = Field(default=None, description="Structured proposal")
    agent_trace: List[str] = Field(default_factory=list, description="Reasoning and tool execution log")
    error: Optional[str] = Field(default=None, description="Error message if failed")
